name: AutoSubmitAction

on:
  watch:
    types: started
  schedule:
    - cron: '0 20 * * *'

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  submit:
    # Name the Job
    name: Submit Health Data
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - uses: nanasess/setup-chromedriver@master
      - name: 'Install requirements'
        run: pip install selenium
      - name: 'Submit'
        env:
          USERID: ${{ secrets.USERID }}
          USERPASS: ${{ secrets.USERPASS }}
        run: python AutoHealthSubmit.py
      - name: 'Get Date'
        run: echo "::set-env name=REPORT_DATE::$(TZ=':Asia/Shenzhen' date '+%Y-%m-%d %T')"
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: 疫情健康申报系统操作结果 (${{env.REPORT_DATE}})
          body: file://email.txt
          to: ${{ secrets.MAIL_RESULT }}
          from: GitHub Actions
          content_type: text/html
      